function PrintJSONfile(PARAMETERS)
% saves a BIDS compatible data dictionary for the events.tsv files

if isempty(which('jsonwrite'))
    
    warning('JSONio package required for writing json data dictionnary: https://github.com/gllmflndn/JSONio.\n See output folder for copies of the JSON files.')

else
    
opts.indent = '    ';

filename = [PARAMETERS.OutputFilename '_events.json'];

switch PARAMETERS.Apperture
    
    case 'Wedge'
        Header = struct(...
            'onset', struct(...
                'LongName', 'stimulus onset', ...
                'Description', 'Time of the event measured from the beginning of the acquisition of the first volume in the corresponding task imaging data file.', ...
                'Levels', 'NA', ...
                'Units', 'seconds'), ...
            'duration', struct(...
                'LongName', 'Duration of the event', ...
                'Description', 'Duration of the event (measured from onset).', ...
                'Levels', 'NA', ...
                'Units', 'seconds'), ...
            'angle', struct(...
                'LongName', 'position of the center of the wedge', ...
                'Description', '', ...
                'Levels', '', ...
                'Units', 'degrees'), ...
            'wedge_angle', struct(...
                'LongName', 'angular width of the wedge', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees'), ...
            'x_target_pos', struct(...
                'LongName', 'x position of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'y_target_pos', struct(...
                'LongName', 'y position of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'target_width', struct(...
                'LongName', 'diameter of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles') );
    
    case 'Bar'
        Header = struct(...
            'onset', struct(...
                'LongName', 'stimulus onset', ...
                'Description', 'Time of the event measured from the beginning of the acquisition of the first volume in the corresponding task imaging data file.', ...
                'Levels', 'NA', ...
                'Units', 'seconds'), ...
            'duration', struct(...
                'LongName', 'Duration of the event', ...
                'Description', 'Duration of the event (measured from onset).', ...
                'Levels', 'NA', ...
                'Units', 'seconds'), ...
            'bar_angle', struct(...
                'LongName', 'bar angle', ...
                'Description', 'bar angle', ...
                'Levels', '', ...
                'Units', 'degrees'), ...
            'bar_width', struct(...
                'LongName', 'width of the bar', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'x_target_pos', struct(...
                'LongName', 'x position of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'y_target_pos', struct(...
                'LongName', 'y position of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'target_width', struct(...
                'LongName', 'diameter of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'bar_position', struct(...
                'LongName', 'bar position', ...
                'Description', 'bar position with respoect to the fixation cross', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
             'stim_file', struct(...
                'LongName', 'stimulus file', ...
                'Description', 'tif file representing the aperture', ...
                'Levels', 'NA', ...
                'Units', 'NA') );
        
    case 'Ring'
        Header = struct(...
            'onset', struct(...
                'LongName', 'stimulus onset', ...
                'Description', 'Time of the event measured from the beginning of the acquisition of the first volume in the corresponding task imaging data file.', ...
                'Levels', 'NA', ...
                'Units', 'seconds'), ...
            'duration', struct(...
                'LongName', 'Duration of the event', ...
                'Description', 'Duration of the event (measured from onset).', ...
                'Levels', 'NA', ...
                'Units', 'seconds'), ...
            'ring_eccentricity', struct(...
                'LongName', 'ring eccentricity', ...
                'Description', 'ring eccentricity', ...
                'Levels', '', ...
                'Units', 'degrees of visual angles'), ...
            'ring_width', struct(...
                'LongName', 'width of the ring', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'x_target_pos', struct(...
                'LongName', 'x position of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'y_target_pos', struct(...
                'LongName', 'y position of the the target', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'scale_outer', struct(...
                'LongName', 'position of the outer rim of the ring', ...
                'Description', '', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles'), ...
            'bar_position', struct(...
                'LongName', 'scale_inner', ...
                'Description', 'position of the inner rim of the ring', ...
                'Levels', 'NA', ...
                'Units', 'degrees of visual angles') );        
        
end

    jsonwrite(filename, Header, opts)

end
    



end