function xy = getXYMotion(xy, dot_nature, hor_vector, vert_vector, pfs)
% xy(dot_nature,3:4) = ...
%     repmat([hor_vector vert_vector], [sum(dot_nature), 1]) ...
%     .* (pfs * rand([sum(dot_nature), 1]));
xy(dot_nature,3:4) = ...
    repmat([hor_vector vert_vector], [sum(dot_nature), 1]) ...
    * pfs ;
end